@startuml

class Playground{
    +«create»Playground()
    +toString(): String
    +addPokemoon(pokemoon: Pokemoon):
    +tcheckPokemoon(player: Player):
}

class Player{
    +«create»Player()
    +pick():
    +choose(pokemoon: String):
    +choose():'pour la machine
    +play(pokemoon: String, enemy: String):
    +play(pokemoon: Integer)'pour la machine
    -getPokemoonByName(name: String): Pokemoon
}

class Deck{
    +«create»Deck()
    +takePokemoon():Pokemoon
}

class Hand{
    +«create»Hand()
    +toString(): String
    +addPokemoon(pokemoon: Pokemoon):
    +usePokemoon():Pokemoon
}

class Discard{
    +«create»Discard()
    +toString(): String
    +addPokemoon():
}

package pokemoon{
    enum Element{
        -m_type: String
        -m_avantage: String
        -m_desavantage: String
        EAU
        TERRE
        FEU
        AIR
        -«create»Element(type: String, avantage: String, desavantage: String)
        +toString(): String
        +getAvantage(): String
        +getDesavantage(): String
    }

    class ListPokemoon{
        -m_namePokemoonAvailable: String[0..21]
        -m_namePokemoonTaken: String[0..21]
        +{static}toStringStat(): String
        -getRandomIndex(): Integer
        +getName(): String
        +reset():
    }

    class PokeLife{
        -m_pv: Integer
        -m_pvMax: Integer
        ~«create»PokeLife(pv: Integer)
        ~getPV(): Integer
        ~getPvMax(): Integer
        ~takeDamage(attack: Integer): Integer
    }

    class PokePower{
        -m_power: Integer
        ~«create»PokePower(power: Integer)
        ~getAttackPower(element: Element, elementEnemi: Element): Integer
        ~getPower(): Integer
    }

    class Pokemoon{
        -m_name: String
        +«create»Pokemoon()
        +toString(): String
        +getName(): String
        +getPower(): Integer
        +getLife(): Integer
        +getLifeMax(): Integer
        +fight(other: Pokemoon):
    }

    Pokemoon "1" *-> "m_life\n1" PokeLife : a
    Pokemoon "1" *-> "m_power\n1" PokePower : a
    Pokemoon "0..*" *-> "m_affinite\n1" Element : est du type

}


Player "1" ---> "-m_deck\n1"Deck : en reserve
Player "1" ---> "-m_hand\n1" Hand : en main
Player "1" ---> "-m_discard\n1" Discard: defausse
Player "2" ---> "-m_playground\n1"Playground : joue sur
Playground "1"---> "-m_pokemoonJ1\n[3]\n\n-m_pokemoonJ2[3]"Pokemoon : en jeux
Pokemoon -[dashed]--> ListPokemoon : uses
Hand "1"--->"-m_pokemoon\n[0..5]" Pokemoon : est faite
Deck "1"---> "-m_pokemoon\n[0..21]"Pokemoon : est fait 
Discard "1"--->"-m_pokemoon\n[0..*]"Pokemoon: est fait


@enduml